# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_language.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from functools import partial
from pathlib import Path

sys.path.append(str(Path(__file__).parents[1]))
from Helper import *
from Log import LogManager
from Settings import Setup as sp
        
class Setup_Field(QDialog):
    signal = pyqtSignal(list)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.sp = sp.Settings()
        self.setupUI_Field()

    @AutomationFunctionDecorator
    def setupUI_Field(self):
        # 해상도 받아옴
        screen = QDesktopWidget().screenGeometry()
        minimum_width = screen.width() * 0.2

        self.setMinimumWidth(minimum_width)
        self.setWindowTitle("엑셀필드 설정")

        # 전체 화면 배치
        self.verticalLayout = QVBoxLayout(self)

        # Setup.ini 파일에 데이터를 창에 표시
        fieldList, _ = self.sp.read_setup(table = "Field")
        check_first = True

        for i in range(6):
            globals()[f'horizontalLayout{i}'] = QHBoxLayout()

            globals()[f'label{i}'] = QLabel()
            globals()[f'label{i}'].setText(f"{i+1}")
            globals()[f'horizontalLayout{i}'].addWidget(globals()[f'label{i}'])

            globals()[f'lineEdit{i}'] = QLineEdit()
            globals()[f'horizontalLayout{i}'].addWidget(globals()[f'lineEdit{i}'])
            self.verticalLayout.addLayout(globals()[f'horizontalLayout{i}'])
            try:
                globals()[f'lineEdit{i}'].setText(fieldList[i])
            except:
                pass

            # 포커스 설정: 빈칸 혹은 마지막칸
            if (globals()[f'lineEdit{i}'].text() == "" or i==5) and check_first:
                globals()[f'lineEdit{i}'].setFocus()
                check_first = False

        # [확인], [취소] 버튼
        self.ok_horizontalLayout = QHBoxLayout()
        self.ok_horizontalLayout.setAlignment(Qt.AlignRight)
        
        self.ok_Button = QPushButton("확인", self)
        self.ok_horizontalLayout.addWidget(self.ok_Button)
        self.cancel_Button = QPushButton("취소", self)
        self.ok_horizontalLayout.addWidget(self.cancel_Button)
        self.verticalLayout.addLayout(self.ok_horizontalLayout)

        # 버튼 이벤트 함수
        self.sl_set_slot()

    @AutomationFunctionDecorator
    def sl_set_slot(self):
        self.ok_Button.clicked.connect(partial(self.ok_Button_clicked))
        self.cancel_Button.clicked.connect(self.close)

    @AutomationFunctionDecorator
    def ok_Button_clicked(self, litter):
        LogManager.HLOG.info("필드 설정 팝업 확인 버튼 선택")
        fieldList = []

        # 중복 체크
        for i in range(6):
            if globals()[f'lineEdit{i}'].text() != "":
                if globals()[f'lineEdit{i}'].text() not in fieldList:
                    fieldList.append(globals()[f'lineEdit{i}'].text())
                else:
                    QMessageBox.about(self, '주의', '중복 라인이 있습니다.')
                    LogManager.HLOG.info("필드 설정 팝업에서 중복 라인 알림 표시")
                    return

        self.sp.config["Field"] = {}
        for i in range(6):
            self.sp.write_setup(table = "Field", 
                                count=i, 
                                val=globals()[f'lineEdit{i}'].text(),
                                val2=None)
            LogManager.HLOG.info(f"필드 설정 팝업에 {globals()[f'lineEdit{i}'].text()} 추가")
        if fieldList == []:
            fieldList = ["OK"]
        self.signal.emit(fieldList)
        self.destroy()
        
    @AutomationFunctionDecorator
    def closeEvent(self, event) -> None:
        LogManager.HLOG.info("필드 설정 팝업 취소 버튼 선택")
        setupList, _ = self.sp.read_setup("Field")
        lineList = [globals()[f'lineEdit{i}'].text() for i in range(6)]

        if setupList != lineList:
            reply = QMessageBox.question(self, '알림', '변경사항이 있습니다.\n취소하시겠습니까?',
                                    QMessageBox.Yes | QMessageBox.No, QMessageBox.No)

            if reply == QMessageBox.Yes:
                LogManager.HLOG.info("필드 설정 팝업 > 취소 > 변경사항 알림에서 예 선택")
                event.accept()
                self.signal.emit([])
            else:
                LogManager.HLOG.info("필드 설정 팝업 > 취소 > 변경사항 알림에서 취소 선택")
                event.ignore()
        else:
            self.signal.emit([])

                
    @AutomationFunctionDecorator
    def keyPressEvent(self, a0: QKeyEvent) -> None:
        
        KEY_ENTER = 16777220
        KEY_SUB_ENTER = 16777221
        KEY_CLOSE = 16777216

        print (f"a0.key() : {a0.key()}")
        if a0.key() == KEY_ENTER or a0.key() == KEY_SUB_ENTER:
            self.ok_Button_clicked(None)
        elif a0.key() == KEY_CLOSE:
            self.close()

if __name__ == "__main__":
    LogManager.Init()
    app = QApplication(sys.argv)
    ui = Setup_Field()
    ui.show()
    sys.exit(app.exec_())
